backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "posts"
    name: "code_posts"
    folder: "posts"
    create: true
    delete: true
    fields:
      - {
          label: "date",
          name: "date_time",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Title", name: "title", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "ImageHandler", name: "thumbnail", widget: "image" }
